[2024-04-26T14:33:53.079+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T14:33:53.286+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tweets_dag.init_tweets_db manual__2024-04-26T14:31:22.546432+00:00 [queued]>
[2024-04-26T14:33:53.351+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tweets_dag.init_tweets_db manual__2024-04-26T14:31:22.546432+00:00 [queued]>
[2024-04-26T14:33:53.357+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-26T14:33:53.449+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): init_tweets_db> on 2024-04-26 14:31:22.546432+00:00
[2024-04-26T14:33:53.532+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tweets_dag', 'init_tweets_db', 'manual__2024-04-26T14:31:22.546432+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/twitter_data_dag.py', '--cfg-path', '/tmp/tmpq4xmklv0']
[2024-04-26T14:33:53.549+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2574) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T14:33:53.598+0000] {standard_task_runner.py:63} INFO - Started process 2590 to run task
[2024-04-26T14:33:53.597+0000] {standard_task_runner.py:91} INFO - Job 136: Subtask init_tweets_db
[2024-04-26T14:33:53.916+0000] {task_command.py:426} INFO - Running <TaskInstance: tweets_dag.init_tweets_db manual__2024-04-26T14:31:22.546432+00:00 [running]> on host 0ceb125076fc
[2024-04-26T14:33:54.299+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stan' AIRFLOW_CTX_DAG_ID='tweets_dag' AIRFLOW_CTX_TASK_ID='init_tweets_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-26T14:31:22.546432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-26T14:31:22.546432+00:00'
[2024-04-26T14:33:54.304+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T14:33:54.386+0000] {sql.py:276} INFO - Executing: CREATE TABLE positive_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE negative_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE neutral_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

[2024-04-26T14:33:54.427+0000] {base.py:84} INFO - Using connection ID 'tweets_localhost' for task execution.
[2024-04-26T14:33:54.461+0000] {base.py:84} INFO - Using connection ID 'tweets_localhost' for task execution.
[2024-04-26T14:33:54.500+0000] {sql.py:457} INFO - Running statement: CREATE TABLE positive_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE negative_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE neutral_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);
, parameters: None
[2024-04-26T14:33:54.515+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T14:33:54.517+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "positive_tweets" already exists

[2024-04-26T14:33:54.541+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=tweets_dag, task_id=init_tweets_db, execution_date=20240426T143122, start_date=20240426T143353, end_date=20240426T143354
[2024-04-26T14:33:54.577+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 136 for task init_tweets_db (relation "positive_tweets" already exists
; 2590)
[2024-04-26T14:33:54.608+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T14:33:54.637+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T14:33:54.640+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
