[2024-05-06T07:15:51.787+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T07:15:51.906+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tweets_dag_v4.init_tweets_db scheduled__2024-05-05T00:00:00+00:00 [queued]>
[2024-05-06T07:15:51.938+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tweets_dag_v4.init_tweets_db scheduled__2024-05-05T00:00:00+00:00 [queued]>
[2024-05-06T07:15:51.940+0000] {taskinstance.py:2303} INFO - Starting attempt 9 of 14
[2024-05-06T07:15:51.994+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): init_tweets_db> on 2024-05-05 00:00:00+00:00
[2024-05-06T07:15:52.087+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tweets_dag_v4', 'init_tweets_db', 'scheduled__2024-05-05T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/twitter_data_dag.py', '--cfg-path', '/tmp/tmpr_6grrct']
[2024-05-06T07:15:52.115+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask init_tweets_db
[2024-05-06T07:15:52.121+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=476) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-06T07:15:52.124+0000] {standard_task_runner.py:63} INFO - Started process 603 to run task
[2024-05-06T07:15:53.061+0000] {task_command.py:426} INFO - Running <TaskInstance: tweets_dag_v4.init_tweets_db scheduled__2024-05-05T00:00:00+00:00 [running]> on host 693d3eace786
[2024-05-06T07:15:53.427+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stan' AIRFLOW_CTX_DAG_ID='tweets_dag_v4' AIRFLOW_CTX_TASK_ID='init_tweets_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-05T00:00:00+00:00'
[2024-05-06T07:15:53.430+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T07:15:53.507+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS positive_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE IF NOT EXISTS negative_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE IF NOT EXISTS neutral_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

TRUNCATE TABLE positive_tweets;
TRUNCATE TABLE negative_tweets;
TRUNCATE TABLE neutral_tweets;

[2024-05-06T07:15:53.543+0000] {base.py:84} INFO - Using connection ID 'tweets_localhost' for task execution.
[2024-05-06T07:15:53.587+0000] {base.py:84} INFO - Using connection ID 'tweets_localhost' for task execution.
[2024-05-06T07:15:53.615+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T07:15:53.617+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 54321 failed: FATAL:  database "tweets" does not exist

[2024-05-06T07:15:53.649+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=tweets_dag_v4, task_id=init_tweets_db, execution_date=20240505T000000, start_date=20240506T071551, end_date=20240506T071553
[2024-05-06T07:15:53.698+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 75 for task init_tweets_db (connection to server at "host.docker.internal" (192.168.65.254), port 54321 failed: FATAL:  database "tweets" does not exist
; 603)
[2024-05-06T07:15:53.816+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-06T07:15:53.945+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-05-06T07:15:53.980+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T07:15:53.989+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
